apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}-configmap
data:
  pgadmin-username: {{ .Values.config.username }}
  pgadmin-email: {{ .Values.config.email }}
  pgadmin-url: {{ .Values.config.url }}
